perks:
  detonation:
    duration: 30
    power: 5 #
  lightning_tempo:
    duration: 30 #
    power: 5 # how fast
  miners_aura:
    duration: 30 #
    power: 5 # radius
  prosperity:
    duration: 40 #
  sonar_sense:
    duration: 30 #
  hercules_might:
    duration: 30 #
    break_duration: 15 #
